services:
  - type: web
    name: phishguard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SAFE_BROWSING_API_KEY
        sync: false
      - key: VIRUSTOTAL_API_KEY
        sync: false
